# -*- coding: utf-8 -*-
"""ClarisseAmaral_lista10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1slTdcGJON2D8WgviZ4Q1xgc-OG9fx3XU

# <font color='blue'>FUMEC - Analytics com Python</font>
## **Lista de exercícios 09 - Preparação de dados**

<br>**ATENÇÃO:** para salvar o arquivo .ipynb do notebook, faça da seguinte forma:

* **Google Colaboratory**: opção do menu "Arquivo --> Fazer download --> Baixar o .ipynb"

* Salve o arquivo com o nome "**SeuNome_lista10.ipynb**"

<br>

### **Importar o arquivo de dados**:

Importar o arquivo de dados "**dados_portuarios.csv**" para o Google Colab.
"""

import pandas as pd
import numpy as np  #biblioteca necessária para trabalhar com os vetores e matrizes
import matplotlib.pyplot as plt #biblioteca utilizada para construir os gráficos
import seaborn as sns

"""### **01) Carregar e preparar o dataset para a regressão**:

Explorar o dataset "**dados_portuarios.csv**" utilizando os recursos da biblioteca Pandas.


"""

data = pd.read_csv('https://drive.google.com/uc?export=download&id=1zJhnnDm1qd8qeCPCSN-rpWlwlqS0Zc7I')
data.head()

"""Selecionar apenas as colunas **declared_quantity**, **declared_cost**, **declared_weight**, **actual_weight** e **days_in_transit** do dataset"""

data[['declared_quantity',
      'declared_cost',
      'declared_weight',
      'actual_weight',
      'days_in_transit']]

"""Listar o total de valores nulos (ausentes) em cada coluna"""

data.isnull().sum()

"""Preencher os valores nulos com a média dos valores

"""

data["actual_weight"] = data["actual_weight"].fillna(data["actual_weight"].mean())
data["declared_weight"] = data["declared_weight"].fillna(data["declared_weight"].mean())

"""Listar novamente o total de valores nulos de cada coluna"""

data.isnull().sum()

"""### **02) Realizar a análise exploratória e preparação de dados**:

Verificar se existem **ouliers**, usando o **bloxplot**, para todas as colunas
"""

#identificando possíveis outliers
import math
def show_bloxplot(df, colunas=[], maxcols=6, scale=1.5):
    if type(colunas) is str:
        df.boxplot(column=[colunas], whis=scale)
    else:
        if len(colunas) == 0:
            colunas = df.select_dtypes(include=np.number).columns
        if maxcols > len(colunas): maxcols = len(colunas)
        maxlins = math.ceil(len(colunas) / maxcols)
        fig, ax = plt.subplots(nrows=maxlins, ncols=maxcols, figsize = (4*maxcols,4*maxlins))
        lin = col = 0
        for atrib in colunas:
            if maxlins == 1:
                df.boxplot( column=[atrib], ax=ax[col], whis=scale )
            else:
                df.boxplot( column=[atrib], ax=ax[lin,col], whis=scale )
            col += 1
            if col == maxcols:
                col = 0
                lin += 1
        plt.show()

show_bloxplot(data)

"""Liste as linhas onde foram encontrados outliers usando o z-score para a coluna **days_in_transit**"""

media = data['days_in_transit'].mean()
desvio = data['days_in_transit'].std()

z_scores = (data['days_in_transit'] - media) / desvio

outliers = data[abs(z_scores) > 3]

print(outliers)

"""Liste as linhas onde foram encontrados outliers usando o intervalo do interquartil (IQR) para a coluna **days_in_transit**"""

Q1 = data['days_in_transit'].quantile(0.25)
Q3 = data['days_in_transit'].quantile(0.75)

IQR = Q3 - Q1
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = data[
    (data['days_in_transit'] < limite_inferior) |
    (data['days_in_transit'] > limite_superior)
]

print(outliers)

"""Remova as linhas com outliers (escolha o método)"""

data = data[
    (data['days_in_transit'] >= limite_inferior) &
    (data['days_in_transit'] <= limite_superior)
]

"""Confira os ouliers removidos com o boxplot"""

show_bloxplot(data, 'days_in_transit')

"""Faça o gráfico de correlação dos atributos"""

colunas = [
    'declared_quantity',
    'declared_cost',
    'declared_weight',
    'actual_weight',
    'days_in_transit'
]

corr = data[colunas].corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr,
            annot=True,
            cmap='coolwarm',
            fmt='.2f')

plt.title('Correlação entre os atributos')
plt.show()

"""### **03) Realizar a regressão no dataset preparado**:

Selecionando as colunas para a regressão

*   Usar os dados das colunas '**declared_quantity**', '**declared_cost**', '**declared_weight**' e '**days_in_transit**' como variáveis independentes (X)
*   Usar os dados da coluna '**actual_weight**' como variável dependente ou alvo da predição da regressão (y)
"""

# Realizando a análise de regressão
X = data[['declared_quantity', 'declared_cost', 'declared_weight', 'days_in_transit']].values  #variáveis independentes
y = data['actual_weight'].values #variável dependente

X[:5]

y[:5]

"""Realizar a normalização dos dados com o `MinMaxScaler`"""

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_normalizado = scaler.fit_transform(X)

"""Separar os dados normalizados em conjuntos de treino e teste"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_normalizado,
    y,
    test_size=0.2,
    random_state=42
)

X_train.shape, X_test.shape

"""Realize a previsão usando a regressão linear, apresentando o R2 e o MSE"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

modelo = LinearRegression()
modelo.fit(X_train, y_train)
y_pred = modelo.predict(X_test)

r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("R² =", r2)
print("MSE =", mse)

"""Regressão usando floresta de árvores de decisão, apresentando o R2 e o MSE"""

from sklearn.ensemble import RandomForestRegressor

modelo_rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

modelo_rf.fit(X_train, y_train)

y_pred_rf = modelo_rf.predict(X_test)
r2_rf = r2_score(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)

print("R²:", r2_rf)
print("MSE:", mse_rf)

"""Regressão usando SVR(kernel='linear', C=1e3), apresentando o R2 e o MSE"""

from sklearn.svm import SVR

modelo_svr = SVR(
    kernel='linear',
    C=1e3
)

modelo_svr.fit(X_train, y_train)

y_pred_svr = modelo_svr.predict(X_test)

r2_svr = r2_score(y_test, y_pred_svr)
mse_svr = mean_squared_error(y_test, y_pred_svr)

print("R² (SVR):", r2_svr)
print("MSE (SVR):", mse_svr)